// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "LLMAB",
    platforms: [
        .macOS(.v14),
        .iOS(.v17)
    ],
    products: [
        .library(name: "LLMCore", targets: ["LLMCore"]),
        .library(name: "RuntimeOllama", targets: ["RuntimeOllama"]),
        .library(name: "RuntimeMLX", targets: ["RuntimeMLX"]),
        .library(name: "RuntimeLlamaCpp", targets: ["RuntimeLlamaCpp"]),
        .library(name: "RuntimeOpenAICompatible", targets: ["RuntimeOpenAICompatible"]),
        .library(name: "ModelRegistry", targets: ["ModelRegistry"]),
        .library(name: "AgentKit", targets: ["AgentKit"]),
        .library(name: "MediaKit", targets: ["MediaKit"]),
        .library(name: "UIKitOmega", targets: ["UIKitOmega"]),
        .executable(name: "llmab", targets: ["llmab"])
        // NOTE: LLMABApp is no longer a SwiftPM executableTarget. The macOS
        // app is generated by XcodeGen from `project.yml` and built with
        // xcodebuild so it produces a proper .app bundle (required for
        // SwiftUI App lifecycle on macOS). See apps/LLMAB-macOS/BUILD.md.
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.3.0")
    ],
    targets: [
        .target(
            name: "LLMCore",
            path: "packages/LLMCore/Sources/LLMCore"
        ),
        .testTarget(
            name: "LLMCoreTests",
            dependencies: ["LLMCore"],
            path: "packages/LLMCore/Tests/LLMCoreTests"
        ),
        .target(
            name: "RuntimeOllama",
            dependencies: ["LLMCore"],
            path: "packages/RuntimeOllama/Sources/RuntimeOllama"
        ),
        .testTarget(
            name: "RuntimeOllamaTests",
            dependencies: ["RuntimeOllama", "LLMCore"],
            path: "packages/RuntimeOllama/Tests/RuntimeOllamaTests"
        ),
        .target(
            name: "RuntimeMLX",
            dependencies: ["LLMCore"],
            path: "packages/RuntimeMLX/Sources/RuntimeMLX"
        ),
        .target(
            name: "RuntimeLlamaCpp",
            dependencies: ["LLMCore"],
            path: "packages/RuntimeLlamaCpp/Sources/RuntimeLlamaCpp"
        ),
        .testTarget(
            name: "RuntimeLlamaCppTests",
            dependencies: ["RuntimeLlamaCpp", "LLMCore"],
            path: "packages/RuntimeLlamaCpp/Tests/RuntimeLlamaCppTests"
        ),
        .target(
            name: "RuntimeOpenAICompatible",
            dependencies: ["LLMCore"],
            path: "packages/RuntimeOpenAICompatible/Sources/RuntimeOpenAICompatible",
            linkerSettings: [
                .linkedFramework("Security", .when(platforms: [.macOS, .iOS]))
            ]
        ),
        .testTarget(
            name: "RuntimeOpenAICompatibleTests",
            dependencies: ["RuntimeOpenAICompatible", "LLMCore"],
            path: "packages/RuntimeOpenAICompatible/Tests/RuntimeOpenAICompatibleTests"
        ),
        .target(
            name: "ModelRegistry",
            dependencies: ["LLMCore", "RuntimeOllama", "RuntimeMLX", "RuntimeLlamaCpp", "RuntimeOpenAICompatible"],
            path: "packages/ModelRegistry/Sources/ModelRegistry"
        ),
        .testTarget(
            name: "ModelRegistryTests",
            dependencies: ["ModelRegistry", "LLMCore"],
            path: "packages/ModelRegistry/Tests/ModelRegistryTests"
        ),
        .target(
            name: "AgentKit",
            dependencies: ["LLMCore"],
            path: "packages/AgentKit/Sources/AgentKit"
        ),
        .testTarget(
            name: "AgentKitTests",
            dependencies: ["AgentKit", "LLMCore"],
            path: "packages/AgentKit/Tests/AgentKitTests"
        ),
        .target(
            name: "MediaKit",
            dependencies: ["LLMCore"],
            path: "packages/MediaKit/Sources/MediaKit",
            linkerSettings: [
                .linkedFramework("AVFoundation", .when(platforms: [.macOS, .iOS])),
                .linkedFramework("Speech",       .when(platforms: [.macOS, .iOS])),
                .linkedFramework("CoreImage",    .when(platforms: [.macOS, .iOS])),
                .linkedFramework("AppKit",       .when(platforms: [.macOS]))
            ]
        ),
        .testTarget(
            name: "MediaKitTests",
            dependencies: ["MediaKit", "LLMCore"],
            path: "packages/MediaKit/Tests/MediaKitTests"
        ),
        .target(
            name: "UIKitOmega",
            path: "packages/UIKitOmega/Sources/UIKitOmega"
        ),
        .testTarget(
            name: "UIKitOmegaTests",
            dependencies: ["UIKitOmega"],
            path: "packages/UIKitOmega/Tests/UIKitOmegaTests"
        ),
        .executableTarget(
            name: "llmab",
            dependencies: [
                "LLMCore",
                "ModelRegistry",
                "RuntimeOllama",
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ],
            path: "cli/llmab/Sources/llmab"
        )
    ]
)
